name: Go Build and Release

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.22.x]
        include:
          - os: ubuntu-latest
            extension: ""
          - os: macos-latest
            extension: ""
          - os: windows-latest
            extension: ".exe"
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      
      - name: Build
        run: go build

      - name: Zip the artifact
        shell: bash
        run: |
          if [ "${{ runner.os }}" = "Windows-latest" ]; then
            7z a genlrtsky-${{ runner.os }}-amd64.zip genlrtsky.exe
          else
            zip genlrtsky-${{ runner.os }}-amd64.zip genlrtsky
          fi
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: genlrtsky-${{ runner.os }}-amd64.zip
          path: genlrtsky-${{ runner.os }}_amd64.zip
      
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      
      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./genlrtsky-ubuntu-amd64.zip
          asset_name: genlrtsky-linux-amd64.zip
          asset_content_type: application/zip

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./genlrtsky-macos-amd64.zip
          asset_name: genlrtsky-macos-amd64.zip
          asset_content_type: application/zip

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./genlrtsky-windows-amd64.zip
          asset_name: genlrtsky-windows-amd64.zip
          asset_content_type: application/zip

